[package]
name = "mikan-rss-downloader"
version = "1.6.6"
description = "Mikan RSS downloader for BitComet"
authors = ["CaptainRuby"]
edition = "2021"

[lib]
name = "mikan_rss_downloader_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
chrono = { version = "0.4.42", default-features = false, features = ["clock", "serde"] }
aes = "0.8.4"
base64 = "0.22.1"
cbc = { version = "0.1.2", features = ["alloc", "block-padding"] }
hex = "0.4.3"
hmac = "0.12.1"
pbkdf2 = "0.12.2"
rand = "0.8.5"
regex = "1.12.2"
reqwest = { version = "0.12.28", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "json", "rustls-tls-native-roots", "socks", "system-proxy"] }
rfd = "0.15.4"
roxmltree = "0.20.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha1 = "0.10.6"
sha2 = "0.10.9"
tauri = { version = "2.11.1", features = ["tray-icon"] }
tauri-plugin-single-instance = "2.4.0"
url = "2.5.7"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Storage_FileSystem"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
